image:
  file: gitpod/Dockerfile

#workspaceLocation: '.'
#checkoutLocation: '/workspace'

jetbrains:
  intellij:
    vmoptions: '-Xmx4g'

vscode:
  extensions:
    - vscjava.vscode-spring-boot-dashboard
    - redhat.java
    - MoBalic.jetbrains-new-dark
    - donjayamanne.git-extension-pack
    - vscjava.vscode-java-pack
    - gitpod.gitpod-desktop

additionalRepositories:
    - url: https://github.com/zzbbll/kubernetes-starter
      checkoutLocation: others

tasks:
  - before: echo "before task..."
    init: echo "init task..."
    command: echo "init command..."
  - name: "build project..."
    init: chmod 755 ./gradlew && ./gradlew build --build-cache -x test
    command: "prepare startup application..."
  - name: "other project"
    init: echo "init other project..."
    command: echo "command other project..."
