image:
  file: gitpod/Dockerfile

#workspaceLocation: '.'
checkoutLocation: '/workspace'

jetbrains:
  intellij:
    vmoptions: '-Xmx4g'

tasks:
  - before: echo "before task..."
    init: echo "init task..."
    command: |
      sdk list java
      sdk list gradle
